---
  - name: Update apt cache
    apt: update_cache=yes
  - name: Upgrade packages
    apt: upgrade=dist

  - name: Install ruby and rubygems and required packages
    apt: "name={{ item }} state=present"
    with_items:
      - ruby-full
      - ruby-bundler
      - build-essential
      - git
  - name: Create directory if they don't exist
    file:
      path: /home/appuser/app
      state: directory
      owner: appuser
      group: appuser
      mode: 0775
  - name: Git clone app
    git:
      repo: https://github.com/express42/reddit.git
      dest: /home/appuser/app
      version: monolith
  - name: bundle install
    bundler:
      state: present
      chdir: /home/appuser/app
  - name: Add unit file for Puma
    template:
      src: puma.service.j2
      dest: /etc/systemd/system/puma.service
      mode: 0644

...
