before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-08/run.sh |
  bash
dist: trusty
language: bash
sudo: required
notifications:
  slack:
    rooms:
      secure: sHx674vUi51S7i+iOWt4yerQoI+xm6OIUnR5QE5raQAesoTa621s37L01f35jc8mVhW6FQYTkLpI0D9bEiaVeNQaVSGn7QJkBoRAPtbWgJkkEWZB2+KhpGajp3wQXVn0PZjNWrpAfEWmwBBy6Iz4n304qlVThFjMDokjexs2rT1oWKTYxjjFCdUEQcGsfcCtJVHLlIc6T9GLlO1/iDsubeGvhBwr+0LClxbc62CmlCKzEBLzQghZrnlYoB4MVQ4Z5WfJEtdSW12ylh1Ar6k4vdiogPIOeSEl1L2WDuCNPky0o2zHHmXQKckpezHvnzc3EB+uI4IbeBw3GsOoOIxyKrzNGQe41pQoKAApggz7S6gyuhja+3pOG/gEOKMbDWfbTM/TUIGj5uH0KHqaQ8Ok2psbFdBc9qrvfxV2vFsLUXHuxH6x5uiKtm4tq4RvT0I4LWheGJR2+mKiA1wtF+eSM8stAptQNLQ8pioNrBHqkzPJvJflD4Or1cs+ExwcSGwpj/iSuEZ97wp1riVQEJpLxr/MTtIAH64MPnFc6pg7DFY/E9Blzxy6+Nb19jsriEVhH2bj4D1yKbKRIz5obNkG9AbUUNZT3wvBsBxtAk6uC+BCs9JcfenHfl2aPi+y6iiwVBF7syTT/ApJ4WSSxbUH8Rgl+b1Cx4kJsa+MoIYfKyE=
