---
- name: Update systemd
  hosts: all
  become: true
  tasks:
  - name: Update apt cache
    apt: update_cache=yes
  - name: Upgrade packages
    apt: upgrade=dist

- name: Install MongoDB
  hosts: all
  become: true
  tasks:
  - name: Add APT key
    shell: wget -qO - https://www.mongodb.org/static/pgp/server-3.2.asc | sudo apt-key add -
  - name: Add APT repository
    apt_repository:
      repo: deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present

  - name: Install mongodb
    apt:
      name: mongodb-org
      state: present

  - name: systemctl enable mongod
    systemd:
      name: mongod
      enabled: yes
...
